appDev:
  image: books-fe-polymer-dev
  volumes:
    - app:/app
  ports:
    - 8081:3000
nginxDev:
  image: nginx:1.10.2
  volumes:
    - /vagrant/conf/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - 8080:80
booksServiceDev:
  image: vfarcic/books-service
  volumes:
    - /data/tests/db:/data/db
  ports:
      - 8082:8080
