FROM ubuntu:14.04
MAINTAINER Viktor Farcic "viktor@farcic.com"

# NodeJS, Git, bzip2
RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup_4.x | bash - && \
    apt-get -y install nodejs git bzip2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Gulp, bower
RUN npm install -g gulp bower

# Source
ADD bower.json /bower.json
ADD gulpfile.js /gulpfile.js
ADD package.json /package.json

#adjust git config
#RUN git config --global url."https://".insteadOf git:// 

# Dependencies
RUN npm install && bower install --allow-root --config.interactive=false -s

# Scripts
ADD dev.sh /dev.sh
RUN chmod +x /dev.sh

CMD ["/dev.sh"]
