#- name: Add Docker repository and update apt cache
#  apt_repository:
#    repo: deb https://get.docker.com/ubuntu docker main
#    update_cache: yes
#    state: present
#  tags: [docker]
  
# lxc-docker與docker-engine實在不同
#- name: Docker is present
#  apt:
#    name: lxc-docker
#    state: latest
#    update_cache: yes
#    force: yes
#  tags: [docker]
- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} main
    update_cache: yes
    state: present
  tags: [docker]
  
- name: Debian Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Debian python-pip is present
  apt:
    name: python-pip
    state: present
    force: yes
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.10.3
    state: present
  tags: [docker]

- name: Debian files are present
  template:
    src: "{{ docker_cfg }}"
    dest: "{{ docker_cfg_dest }}"
  register: copy_result
  tags: [docker]
  
- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed and is_systemd is defined
  tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
  tags: [docker]
  
- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.8.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  tags: [docker]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker]
